In [2]:
# Numpy Array Manupulation

In [3]:
import numpy as np

In [4]:
arr = np.random.randint(1,10 , (3,4))

In [5]:
arr

array([[8, 5, 9, 1],
       [4, 5, 3, 2],
       [5, 7, 7, 4]])

In [6]:
arr.reshape(6 , 2)

array([[8, 5],
       [9, 1],
       [4, 5],
       [3, 2],
       [5, 7],
       [7, 4]])

In [7]:
arr.reshape(2 , 6)

array([[8, 5, 9, 1, 4, 5],
       [3, 2, 5, 7, 7, 4]])

In [9]:
arr.reshape(2 , -41235252)

array([[8, 5, 9, 1, 4, 5],
       [3, 2, 5, 7, 7, 4]])

In [11]:
arr.T

array([[8, 4, 5],
       [5, 5, 7],
       [9, 3, 7],
       [1, 2, 4]])

In [12]:
arr

array([[8, 5, 9, 1],
       [4, 5, 3, 2],
       [5, 7, 7, 4]])

In [14]:
# to convert 2D array into 1Darray
arr.flatten()

array([8, 5, 9, 1, 4, 5, 3, 2, 5, 7, 7, 4])

In [15]:
arr1 =  np.array([1,2,3,3,4])

In [17]:
arr1.ndim

1

In [18]:
# to change 1D array into 2D array
np.expand_dims(arr1 , axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [19]:
np.expand_dims(arr1 , axis=0)

array([[1, 2, 3, 3, 4]])

In [20]:
arr

array([[8, 5, 9, 1],
       [4, 5, 3, 2],
       [5, 7, 7, 4]])

In [21]:
np.squeeze(arr)

array([[8, 5, 9, 1],
       [4, 5, 3, 2],
       [5, 7, 7, 4]])

In [23]:
data = np.array([[1] , [2] , [3]])

In [24]:
data

array([[1],
       [2],
       [3]])

In [25]:
np.squeeze(data)

array([1, 2, 3])

In [26]:
arr1

array([1, 2, 3, 3, 4])

In [27]:
np.repeat(arr1 , 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [28]:
np.roll(arr1 , 3)

array([3, 3, 4, 1, 2])

In [30]:
arr1

array([1, 2, 3, 3, 4])

In [31]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [32]:
# Numpy Binary Operators

In [33]:
arr1 = np.random.randint(1,10 , (3,4))

In [34]:
arr2 = np.random.randint(1,10 , (3,4))

In [35]:
arr1

array([[8, 3, 1, 9],
       [7, 7, 6, 6],
       [3, 6, 8, 9]])

In [36]:
arr2

array([[7, 3, 6, 4],
       [5, 9, 5, 3],
       [4, 2, 6, 1]])

In [37]:
arr1 + arr2

array([[15,  6,  7, 13],
       [12, 16, 11,  9],
       [ 7,  8, 14, 10]])

In [38]:
arr1 * arr2

array([[56,  9,  6, 36],
       [35, 63, 30, 18],
       [12, 12, 48,  9]])

In [39]:
arr1 / arr2

array([[1.14285714, 1.        , 0.16666667, 2.25      ],
       [1.4       , 0.77777778, 1.2       , 2.        ],
       [0.75      , 3.        , 1.33333333, 9.        ]])

In [40]:
arr1 - arr2

array([[ 1,  0, -5,  5],
       [ 2, -2,  1,  3],
       [-1,  4,  2,  8]])

In [41]:
arr1 % arr2

array([[1, 0, 1, 1],
       [2, 7, 1, 0],
       [3, 0, 2, 0]])

In [42]:
arr1 ** arr2

array([[ 2097152,       27,        1,     6561],
       [   16807, 40353607,     7776,      216],
       [      81,       36,   262144,        9]])

In [43]:
arr1

array([[8, 3, 1, 9],
       [7, 7, 6, 6],
       [3, 6, 8, 9]])

In [44]:
arr2

array([[7, 3, 6, 4],
       [5, 9, 5, 3],
       [4, 2, 6, 1]])

In [45]:
arr1 & arr2

array([[0, 3, 0, 0],
       [5, 1, 4, 2],
       [0, 2, 0, 1]])

In [46]:
# nigate of an array
~arr1

array([[ -9,  -4,  -2, -10],
       [ -8,  -8,  -7,  -7],
       [ -4,  -7,  -9, -10]])

In [47]:
arr1 | arr2

array([[15,  3,  7, 13],
       [ 7, 15,  7,  7],
       [ 7,  6, 14,  9]])

In [48]:
arr1 > arr2

array([[ True, False, False,  True],
       [ True, False,  True,  True],
       [False,  True,  True,  True]])

In [49]:
# Numpy String Function

In [52]:
arr = np.array(['sudh' , 'kumar'])

In [53]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [54]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [55]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [56]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [57]:
# Numpy Mathematical Function

In [58]:
arr1

array([[8, 3, 1, 9],
       [7, 7, 6, 6],
       [3, 6, 8, 9]])

In [59]:
np.sin(arr1)

array([[ 0.98935825,  0.14112001,  0.84147098,  0.41211849],
       [ 0.6569866 ,  0.6569866 , -0.2794155 , -0.2794155 ],
       [ 0.14112001, -0.2794155 ,  0.98935825,  0.41211849]])

In [60]:
np.cos(arr1)

array([[-0.14550003, -0.9899925 ,  0.54030231, -0.91113026],
       [ 0.75390225,  0.75390225,  0.96017029,  0.96017029],
       [-0.9899925 ,  0.96017029, -0.14550003, -0.91113026]])

In [61]:
np.tan(arr1)

array([[-6.79971146, -0.14254654,  1.55740772, -0.45231566],
       [ 0.87144798,  0.87144798, -0.29100619, -0.29100619],
       [-0.14254654, -0.29100619, -6.79971146, -0.45231566]])

In [62]:
np.log10(arr1)

array([[0.90308999, 0.47712125, 0.        , 0.95424251],
       [0.84509804, 0.84509804, 0.77815125, 0.77815125],
       [0.47712125, 0.77815125, 0.90308999, 0.95424251]])

In [63]:
np.exp(arr1)

array([[2.98095799e+03, 2.00855369e+01, 2.71828183e+00, 8.10308393e+03],
       [1.09663316e+03, 1.09663316e+03, 4.03428793e+02, 4.03428793e+02],
       [2.00855369e+01, 4.03428793e+02, 2.98095799e+03, 8.10308393e+03]])

In [64]:
np.sqrt(arr1)

array([[2.82842712, 1.73205081, 1.        , 3.        ],
       [2.64575131, 2.64575131, 2.44948974, 2.44948974],
       [1.73205081, 2.44948974, 2.82842712, 3.        ]])

In [65]:
np.power(arr1 , 2)

array([[64,  9,  1, 81],
       [49, 49, 36, 36],
       [ 9, 36, 64, 81]])

In [66]:
np.mean(arr1)

6.083333333333333

In [67]:
np.median(arr1)

6.5

In [69]:
np.std(arr1)

2.43099202430247

In [70]:
np.var(arr1)

5.909722222222222

In [71]:
np.min(arr1)

1

In [72]:
np.max(arr1)

9