In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
# convert list into array
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)   # ndarray means n-dimencional array

numpy.ndarray

In [6]:
np.array([[1,2] , [3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
# array([1, 2, 3, 4]) single [] means one dimencional array.
# array([[1, 2],
#       [3, 4]])  [[]] means two dimencional array

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a = [2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [11]:
b = np.matrix(l)

In [12]:
b

matrix([[1, 2, 3, 4]])

In [13]:
# array is superclass in numpy
# matreix is subset of array in numpy
# matrix is bidifault two dimencitional

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [15]:
a = np.array(l)

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c = a   # it is solawo copy here c and a point to one location where a is present

In [18]:
c

array([1, 2, 3, 4])

In [19]:
a

array([1, 2, 3, 4])

In [20]:
c[0] = 100

In [21]:
c

array([100,   2,   3,   4])

In [22]:
d = np.copy(a)   # it is deep copy . here d and a point to other location

In [23]:
d

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [25]:
a[1] = 400

In [26]:
a

array([100, 400,   3,   4])

In [27]:
d

array([100,   2,   3,   4])

In [28]:
# to generate data using function by given condition here (3,3) means 3 X 3 matrix or 2D array
np.fromfunction(lambda i,j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i,j : i * j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
# to create array from fromiter function it is used for iterable condition
iterable = (i*i for i in range (5))

In [31]:
# to create array from fromiter function it is used for iterable condition
np.fromiter(iterable , float)

array([ 0.,  1.,  4.,  9., 16.])

In [32]:
# to crteate a array from string
np.fromstring('234 234' , sep = ' ')

array([234., 234.])

In [33]:
np.fromstring('4,5' , sep = ',')

array([4., 5.])

In [34]:
# Numpy - Data Types.

In [35]:
l = [2,3,4,5,6]

In [36]:
ar = np.array(l)

In [37]:
ar

array([2, 3, 4, 5, 6])

In [38]:
# to find dimension of an array
ar.ndim

1

In [39]:
ar2 = np.array([[1,2,3,4] , [2,3,4,5]])

In [40]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [41]:
# to find dimension of an array
ar2.ndim

2

In [42]:
# to find the size or how many element present in array
ar.size

5

In [43]:
ar2.size

8

In [44]:
ar

array([2, 3, 4, 5, 6])

In [45]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [46]:
# to find the shape or how many row and column is present in the array
ar.shape

(5,)

In [47]:
ar2.shape

(2, 4)

In [48]:
ar.dtype

dtype('int64')

In [49]:
ar2.dtype

dtype('int64')

In [50]:
ar22 = np.array([(1.4 , 45 ,45) , (23,45,66)])

In [51]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [52]:
ar22.dtype

dtype('float64')

In [53]:
list(range(5))

[0, 1, 2, 3, 4]

In [54]:
list(range(0.1 , 5))

TypeError: 'float' object cannot be interpreted as an integer

In [55]:
# range() function cannot take float value but in numpy arange() function can take floating point also
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [56]:
np.arange(2.3,5.6 , 0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [57]:
list(np.arange(2.3,5.6 , 0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [58]:
# range() func & arange() func is same the only difference is arange() func is allow the float or fractionm value.
# range() func is present in python core & arange function is present in numpy

In [59]:
# to produce array by linespace() func
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.zeros((3,4,2)) # here (3,4,2) is 3 dimensional array means 4 X 2 matrix or array such type array 3 times

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [63]:
ar4 = np.zeros((3,4,2,3))

In [64]:
ar4.ndim

4

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

In [66]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
on = np.ones((2,3,2))

In [68]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [69]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [70]:
# to proiduced empty array
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [71]:
# to produce identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
np.linspace(2,4,20) # to produce 2 to 4 data which is divided by 20

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [73]:
np.logspace(2 , 5 , 10)  # to produce logarithm of 2 to 5 data which is divided by 10

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [74]:
np.logspace(2 , 5 , 10 , base = 2)   # bidifault base = 10

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [75]:
# to produce random data 
arr = np.random.randn(3,4)    # randn produce that type of data where mean = 0 avg = 0 & std = 1

In [76]:
import pandas as pd

In [77]:
pd.DataFrame(arr)

0         1         2         3
0 -0.115251  1.129059 -0.285638  0.316582
1  0.077485  0.002963 -0.093048  0.094706
2  1.098310  0.662737  0.195246  0.093822

In [78]:
np.random.rand(3 , 4)

array([[0.74074892, 0.47257548, 0.71309575, 0.14312455],
       [0.82126553, 0.08819255, 0.18364138, 0.7288519 ],
       [0.60157659, 0.21560373, 0.55272704, 0.84307849]])

In [79]:
np.random.randint(1,110 ,(3,4))    # here the data presejnt in between 1 to 110 and it gives the output 3 X 4 matrix or array it always produce int

array([[ 72, 102,  74,  30],
       [ 52,  89,  53,  88],
       [ 34,  76,   6, 101]])

In [80]:
pd.DataFrame(np.random.randint(1,110 ,(300,400))) 

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     55   39   21   84   96   52   29  103   51   86  ...   43   92  103   
1     56   31   36   15   83   33   15   39   15   84  ...   59   96  108   
2    108   81  105   74    2  109   14   19   10   38  ...   86   78   87   
3    102   90   49   35    4   63   13   20   96   46  ...  102  103   84   
4     18  103   32   85   27   45   32   97   43   41  ...   58   94   84   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295  107   61   71   53   33   14  106   73  107   65  ...   38   39    2   
296   62  109   20   42    8   22   26  106    2  102  ...   61   92   92   
297   31   46   82   89   40   76  102   18   40   52  ...   11   57   68   
298   77  102   24   31   17   54    2   11   16   36  ...   66   10   80   
299   46   13   46   28   75   93   29    6   59   15  ...   25   50   17   

     393  394  395  396  397  398  399  
0      6   55   54   23   99   74   63  
1     34   97   93   82   26   32   33  
2     72   58   21   52    3   86   81  
3     10   62   79    5   95   46    6  
4     44   18   60   12  100    9   38  
..   ...  ...  ...  ...  ...  ...  ...  
295    1   75   89   96   84   10   74  
296   79   40   84   25   21   39   88  
297   25   62   88   56   35   95   90  
298   92   52   80   40  109   24   76  
299   33   62   31   30  106   78   78  

[300 rows x 400 columns]

In [81]:
# to stroe the above data in csv file
pd.DataFrame(np.random.randint(1,110 ,(300,400))).to_csv('test.csv')

In [82]:
arr = np.random.rand(3 , 4)

In [83]:
arr

array([[0.49726413, 0.31627037, 0.24446997, 0.20071051],
       [0.74008776, 0.525021  , 0.0887768 , 0.10549645],
       [0.20451141, 0.23193284, 0.80460971, 0.7071527 ]])

In [84]:
arr.reshape(6,2) # 3 X 4 = 12 data is prtesent means reshape is same as 12 data means 6 X 2

array([[0.49726413, 0.31627037],
       [0.24446997, 0.20071051],
       [0.74008776, 0.525021  ],
       [0.0887768 , 0.10549645],
       [0.20451141, 0.23193284],
       [0.80460971, 0.7071527 ]])

In [85]:
arr.reshape(6,-1)

array([[0.49726413, 0.31627037],
       [0.24446997, 0.20071051],
       [0.74008776, 0.525021  ],
       [0.0887768 , 0.10549645],
       [0.20451141, 0.23193284],
       [0.80460971, 0.7071527 ]])

In [86]:
arr1 = arr.reshape(6,-145248552745)

In [87]:
arr1

array([[0.49726413, 0.31627037],
       [0.24446997, 0.20071051],
       [0.74008776, 0.525021  ],
       [0.0887768 , 0.10549645],
       [0.20451141, 0.23193284],
       [0.80460971, 0.7071527 ]])

In [88]:
arr1[1][1]

0.20071051160702114

In [89]:
arr1[2:5 , 1]

array([0.525021  , 0.10549645, 0.23193284])

In [90]:
arr = np.random.randint(1,100 , (5,5))

In [91]:
arr

array([[42, 94,  6, 44, 12],
       [23, 35, 92, 10,  3],
       [74, 49, 94, 44, 10],
       [17, 87, 67, 10, 63],
       [16, 69, 10, 80, 60]])

In [92]:
arr[arr > 50]

array([94, 92, 74, 94, 87, 67, 63, 69, 80, 60])

In [93]:
arr

array([[42, 94,  6, 44, 12],
       [23, 35, 92, 10,  3],
       [74, 49, 94, 44, 10],
       [17, 87, 67, 10, 63],
       [16, 69, 10, 80, 60]])

In [94]:
arr[2:4 , [1,2]]

array([[49, 94],
       [87, 67]])

In [95]:
arr[0][0] = 5000

In [96]:
arr

array([[5000,   94,    6,   44,   12],
       [  23,   35,   92,   10,    3],
       [  74,   49,   94,   44,   10],
       [  17,   87,   67,   10,   63],
       [  16,   69,   10,   80,   60]])

In [97]:
# Numpy Inbuilt Function

In [98]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [99]:
arr1

array([[2, 2, 2],
       [1, 1, 1],
       [1, 1, 2]])

In [100]:
arr2

array([[2, 2, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [101]:
arr1 + arr2 

array([[4, 4, 4],
       [3, 2, 2],
       [2, 3, 3]])

In [102]:
arr1 - arr2

array([[ 0,  0,  0],
       [-1,  0,  0],
       [ 0, -1,  1]])

In [103]:
arr1 / arr2

array([[1. , 1. , 1. ],
       [0.5, 1. , 1. ],
       [1. , 0.5, 2. ]])

In [107]:
arr1 * arr2   # it is index multiplication

array([[4, 4, 4],
       [2, 1, 1],
       [1, 2, 2]])

In [108]:
arr1

array([[2, 2, 2],
       [1, 1, 1],
       [1, 1, 2]])

In [109]:
arr2

array([[2, 2, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [110]:
# to find matrix multiplication
arr1@arr2

array([[10, 10,  8],
       [ 5,  5,  4],
       [ 6,  7,  5]])

In [111]:
arr1 / 0

/tmp/ipykernel_873/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [113]:
arr1 + 100

array([[102, 102, 102],
       [101, 101, 101],
       [101, 101, 102]])

In [114]:
arr1**2

array([[4, 4, 4],
       [1, 1, 1],
       [1, 1, 4]])

In [115]:
# Numpy - Broadcasting

In [117]:
arr = np.zeros((4,4))

In [118]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [119]:
row = np.array([1,2,3,4])

In [120]:
row

array([1, 2, 3, 4])

In [127]:
arr + row     # this is the broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [123]:
# to rotate one 1D array
row.T     # 1D array can not be rotate

array([1, 2, 3, 4])

In [124]:
col = np.array([[1,2,3,4]])

In [125]:
# to rotate one 2D array
col.T

array([[1],
       [2],
       [3],
       [4]])

In [126]:
col

array([[1, 2, 3, 4]])

In [128]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [129]:
arr1 = np.random.randint(1,4 , (3,4))

In [130]:
arr1

array([[1, 3, 1, 2],
       [1, 2, 1, 3],
       [1, 3, 3, 2]])

In [131]:
# to find squre root of all the array
np.sqrt(arr1)

array([[1.        , 1.73205081, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        , 1.73205081],
       [1.        , 1.73205081, 1.73205081, 1.41421356]])

In [132]:
# to find exponent of all the array
np.exp(arr1)

array([[ 2.71828183, 20.08553692,  2.71828183,  7.3890561 ],
       [ 2.71828183,  7.3890561 ,  2.71828183, 20.08553692],
       [ 2.71828183, 20.08553692, 20.08553692,  7.3890561 ]])

In [133]:
np.log10(arr1)

array([[0.        , 0.47712125, 0.        , 0.30103   ],
       [0.        , 0.30103   , 0.        , 0.47712125],
       [0.        , 0.47712125, 0.47712125, 0.30103   ]])